apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ template "mongodb.fullname" . }}
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/mluser/volumes/mongodb